# Generated by Django 3.1.7 on 2021-03-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdProfesional', models.IntegerField()),
                ('numeroMatric', models.IntegerField()),
                ('especialidad', models.CharField(max_length=20)),
                ('idTipoUsuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPaciente', models.IntegerField()),
                ('IdServProf', models.IntegerField()),
                ('fecha', models.DateField()),
                ('Hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docIdent', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.BooleanField()),
                ('fechaNac', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('seguro', models.BooleanField()),
                ('idTipoUsuario', models.IntegerField()),
            ],
        ),
    ]
